export enum PDF_NAME {
    ENGLISH_SINGLE_APPLICANT_DETAILED = 'CPESINGLEDETAILGAP',
    ENGLISH_MULTI_APPLICANT_DETAILED = 'CPEJOINTDETAILGAP',
    FRENCH_SINGLE_APPLICANT_DETAILED = 'FRENCH_SINGLE_APPLICANT_DETAILED',
    FRENCH_MULTI_APPLICANT_DETAILED = 'FRENCH_MULTI_APPLICANT_DETAILED',
    ENGLISH_SINGLE_APPLICANT_SUMMARY = 'CPESINGLESUMMARYGAP',
    ENGLISH_MULTI_APPLICANT_SUMMARY = 'CPEJOINTSUMMARYGAP',
    FRENCH_SINGLE_APPLICANT_SUMMARY = 'FRENCH_SINGLE_APPLICANT_SUMMARY',
    FRENCH_MULTI_APPLICANT_SUMMARY = 'FRENCH_MULTI_APPLICANT_SUMMARY',
}

export enum APPLICATION_TYPE {
    SINGLE = 'SINGLE_APPLICANT',
    MULTI = 'MULTI_APPLICANT',
}

export enum PDF_LANGUAGE {
    ENGLISH = 'ENGLISH',
    FRENCH = 'FRENCH',
}
export enum PDF_TYPE {
    DETAILED = 'DETAILED',
    SUMMARY = 'SUMMARY',
}