import { EnumValue } from '@core/models/insurance/enum.model';

export const getAddressReferenceTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 1,
    description: 'Member Employment',
    abbreviation: 'MemberEmployment',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 1,
    description: 'Member Asset',
    abbreviation: 'MemberAsset',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 1,
    description: 'Application PAP',
    abbreviation: 'ApplicationPAP',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 1,
    description: 'Application Insurance PAP',
    abbreviation: 'ApplicationInsurancePAP',
    systemValue: '',
    sequence: 4,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 1,
    description: 'Member ID Verification',
    abbreviation: 'MemberIDVerification',
    systemValue: '',
    sequence: 5,
    isDefault: false,
  },
];
export const getAddressStructureTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 2,
    description: 'Civic',
    abbreviation: 'Civic',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 2,
    description: 'POBox',
    abbreviation: 'POBox',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 2,
    description: 'Rural',
    abbreviation: 'Rural',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 2,
    description: 'Military',
    abbreviation: 'Military',
    systemValue: '',
    sequence: 4,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 2,
    description: 'General',
    abbreviation: 'General',
    systemValue: '',
    sequence: 5,
    isDefault: false,
  },
];
export const getAddressTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 3,
    description: 'Home',
    abbreviation: 'Home',
    systemValue: 'Personal',
    sequence: 1,
    isDefault: false,
  },
  {
    id: 2,
    systemEnumId: 3,
    description: 'Vacation Home',
    abbreviation: 'VacationHome',
    systemValue: 'Personal',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 3,
    description: 'Cottage',
    abbreviation: 'Cottage',
    systemValue: 'Personal',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 3,
    description: 'Mailing',
    abbreviation: 'Mailing',
    systemValue: 'Personal',
    sequence: 4,
    isDefault: true,
  },
  {
    id: 5,
    systemEnumId: 3,
    description: 'New Mailing',
    abbreviation: 'NewMailing',
    systemValue: 'Other',
    sequence: 5,
    isDefault: false,
  },
  {
    id: 6,
    systemEnumId: 3,
    description: 'Pre-authorized Debit Account',
    abbreviation: 'PAD',
    systemValue: 'Other',
    sequence: 6,
    isDefault: false,
  },
  {
    id: 7,
    systemEnumId: 3,
    description: 'Beneficiary',
    abbreviation: 'Beneficiary',
    systemValue: 'Other',
    sequence: 7,
    isDefault: false,
  },
];
export const getApplicantTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 4,
    description: 'Primary',
    abbreviation: 'Primary',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 4,
    description: 'Secondary',
    abbreviation: 'Secondary',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 4,
    description: 'Tertiary',
    abbreviation: 'Tertiary',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 4,
    description: 'Quaternary',
    abbreviation: 'Quaternary',
    systemValue: '',
    sequence: 4,
    isDefault: false,
  },
];
export const getApplicationStatusList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 5,
    description: 'Draft',
    abbreviation: 'Draft',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 5,
    description: 'Pending',
    abbreviation: 'Pending',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 5,
    description: 'Submitted',
    abbreviation: 'Submitted',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
];
export const getAddressStatusList = (): EnumValue[] => [
  { id: 1, systemEnumId: 6, description: 'Own', abbreviation: 'Own', systemValue: '', sequence: 1, isDefault: true },
  { id: 2, systemEnumId: 6, description: 'Rent', abbreviation: 'Rent', systemValue: '', sequence: 2, isDefault: false },
  {
    id: 3,
    systemEnumId: 6,
    description: 'Resident',
    abbreviation: 'Resident',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
];
export const getLanguageList = (): EnumValue[] => [
  { id: 1, systemEnumId: 7, description: 'English', abbreviation: 'en', systemValue: '', sequence: 1, isDefault: true },
  { id: 2, systemEnumId: 7, description: 'French', abbreviation: 'fr', systemValue: '', sequence: 2, isDefault: false },
];
export const getChannelTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 8,
    description: 'Branch',
    abbreviation: 'Branch',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 8,
    description: 'Digital',
    abbreviation: 'Digital',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 8,
    description: 'Dealer',
    abbreviation: 'Dealer',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 8,
    description: 'Broker',
    abbreviation: 'Broker',
    systemValue: '',
    sequence: 4,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 8,
    description: 'Mobile Staff',
    abbreviation: 'MobileStaff',
    systemValue: '',
    sequence: 5,
    isDefault: false,
  },
  {
    id: 6,
    systemEnumId: 8,
    description: 'Contact Centre',
    abbreviation: 'ContactCentre',
    systemValue: '',
    sequence: 6,
    isDefault: false,
  },
];
export const getCountryList = (): EnumValue[] => [
  { id: 1, systemEnumId: 9, description: 'Canada', abbreviation: 'CA', systemValue: '', sequence: 1, isDefault: true },
  {
    id: 2,
    systemEnumId: 9,
    description: 'Other',
    abbreviation: 'Other',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
];
export const getCreditTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 10,
    description: 'Mortgage',
    abbreviation: 'Mtg',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  { id: 2, systemEnumId: 10, description: 'Loan', abbreviation: 'LN', systemValue: '', sequence: 2, isDefault: false },
  { id: 3, systemEnumId: 10, description: 'LOC', abbreviation: 'LOC', systemValue: '', sequence: 3, isDefault: false },
];
export const getEmailTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 11,
    description: 'Personal',
    abbreviation: 'Personal',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 11,
    description: 'Work',
    abbreviation: 'Work',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 11,
    description: 'Employer',
    abbreviation: 'Employer',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 99,
    systemEnumId: 11,
    description: 'Other',
    abbreviation: 'Other',
    systemValue: '',
    sequence: 99,
    isDefault: false,
  },
];
export const getPaymentFrequencyList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 12,
    description: 'Accelerated Weekly',
    abbreviation: 'AcceleratedWeekly',
    systemValue: '52',
    sequence: 1,
    isDefault: false,
  },
  {
    id: 2,
    systemEnumId: 12,
    description: 'Weekly',
    abbreviation: 'Weekly',
    systemValue: '52',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 12,
    description: 'Accelerated Bi-Weekly',
    abbreviation: 'AcceleratedBiWeekly',
    systemValue: '26',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 12,
    description: 'Bi-Weekly',
    abbreviation: 'Bi-Weekly',
    systemValue: '26',
    sequence: 4,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 12,
    description: 'Semi-Monthly',
    abbreviation: 'Semi-Monthly',
    systemValue: '24',
    sequence: 5,
    isDefault: false,
  },
  {
    id: 6,
    systemEnumId: 12,
    description: 'Monthly',
    abbreviation: 'Monthly',
    systemValue: '12',
    sequence: 6,
    isDefault: true,
  },
  {
    id: 7,
    systemEnumId: 12,
    description: 'Last Day of Each Month',
    abbreviation: 'LastDayOfEachMonth',
    systemValue: '12',
    sequence: 7,
    isDefault: false,
  },
  {
    id: 8,
    systemEnumId: 12,
    description: 'One Payment',
    abbreviation: 'OnePayment',
    systemValue: '0',
    sequence: 8,
    isDefault: false,
  },
  {
    id: 9,
    systemEnumId: 12,
    description: 'Bi-Monthly',
    abbreviation: 'Bi-Monthly',
    systemValue: '6',
    sequence: 9,
    isDefault: false,
  },
  {
    id: 10,
    systemEnumId: 12,
    description: 'Quarterly',
    abbreviation: 'Quarterly',
    systemValue: '4',
    sequence: 10,
    isDefault: false,
  },
  {
    id: 11,
    systemEnumId: 12,
    description: 'Semi-Annually',
    abbreviation: 'Semi-Annually',
    systemValue: '2',
    sequence: 11,
    isDefault: false,
  },
  {
    id: 12,
    systemEnumId: 12,
    description: 'Annually',
    abbreviation: 'Annually',
    systemValue: '1',
    sequence: 12,
    isDefault: false,
  },
];
export const getFormTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 13,
    description: 'Insurance Form',
    abbreviation: 'InsuranceForm',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 13,
    description: 'Supplemental Form',
    abbreviation: 'SupplementalForm',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 13,
    description: 'Download Only',
    abbreviation: 'DownloadOnly',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
];
export const getGenderList = (): EnumValue[] => [
  { id: 1, systemEnumId: 14, description: 'Male', abbreviation: 'M', systemValue: '', sequence: 1, isDefault: true },
  { id: 2, systemEnumId: 14, description: 'Female', abbreviation: 'F', systemValue: '', sequence: 2, isDefault: false },
  { id: 3, systemEnumId: 14, description: 'Other', abbreviation: 'O', systemValue: '', sequence: 3, isDefault: false },
];
export const getInsuranceTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 15,
    description: 'Single Premium',
    abbreviation: 'SP',
    systemValue: '4',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 15,
    description: 'Mortgage',
    abbreviation: 'MO',
    systemValue: '2',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 15,
    description: 'Line of Credit',
    abbreviation: 'LC',
    systemValue: '2',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 15,
    description: 'Outstanding Balance',
    abbreviation: 'OB',
    systemValue: '2',
    sequence: 4,
    isDefault: false,
  },
];
export const getLoanTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 16,
    description: 'Loan',
    abbreviation: 'PLN',
    systemValue: 'SP',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 16,
    description: 'Mortgage',
    abbreviation: 'PMTG',
    systemValue: 'MO',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 16,
    description: 'Line of Credit',
    abbreviation: 'PLOC',
    systemValue: 'OB',
    sequence: 3,
    isDefault: false,
  },
];
export const getPhoneTypeList = (): EnumValue[] => [
  { id: 1, systemEnumId: 17, description: 'Home', abbreviation: 'Home', systemValue: '', sequence: 1, isDefault: true },
  {
    id: 2,
    systemEnumId: 17,
    description: 'Work',
    abbreviation: 'Work',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 17,
    description: 'Mobile',
    abbreviation: 'Mobile',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
];
export const getProvinceList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 18,
    description: 'Alberta',
    abbreviation: 'AB',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 18,
    description: 'British Columbia',
    abbreviation: 'BC',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 18,
    description: 'Manitoba',
    abbreviation: 'MB',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 18,
    description: 'New Brunswick',
    abbreviation: 'NB',
    systemValue: '',
    sequence: 4,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 18,
    description: 'Newfoundland and Labrador',
    abbreviation: 'NL',
    systemValue: '',
    sequence: 5,
    isDefault: false,
  },
  {
    id: 6,
    systemEnumId: 18,
    description: 'Nova Scotia',
    abbreviation: 'NS',
    systemValue: '',
    sequence: 6,
    isDefault: false,
  },
  {
    id: 7,
    systemEnumId: 18,
    description: 'Ontario',
    abbreviation: 'ON',
    systemValue: '',
    sequence: 7,
    isDefault: false,
  },
  {
    id: 8,
    systemEnumId: 18,
    description: 'Prince Edward Island',
    abbreviation: 'PE',
    systemValue: '',
    sequence: 8,
    isDefault: false,
  },
  {
    id: 9,
    systemEnumId: 18,
    description: 'Quebec',
    abbreviation: 'QC',
    systemValue: '',
    sequence: 9,
    isDefault: false,
  },
  {
    id: 10,
    systemEnumId: 18,
    description: 'Saskatchewan',
    abbreviation: 'SK',
    systemValue: '',
    sequence: 10,
    isDefault: false,
  },
  {
    id: 11,
    systemEnumId: 18,
    description: 'Yukon',
    abbreviation: 'YT',
    systemValue: '',
    sequence: 11,
    isDefault: false,
  },
  {
    id: 12,
    systemEnumId: 18,
    description: 'Northwest Territories',
    abbreviation: 'NT',
    systemValue: '',
    sequence: 12,
    isDefault: false,
  },
  {
    id: 13,
    systemEnumId: 18,
    description: 'Nunavut',
    abbreviation: 'NU',
    systemValue: '',
    sequence: 13,
    isDefault: false,
  },
  {
    id: 14,
    systemEnumId: 18,
    description: 'Other',
    abbreviation: 'OT',
    systemValue: '',
    sequence: 14,
    isDefault: false,
  },
];
export const getWaiverReasonStatusList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 19,
    description: 'Insured',
    abbreviation: 'Insured',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 19,
    description: 'Waived',
    abbreviation: 'Waived',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 19,
    description: 'Ineligible',
    abbreviation: 'Ineligible',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
];
export const getSegmentTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 20,
    description: 'Retail',
    abbreviation: 'Retail',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 20,
    description: 'Agriculture',
    abbreviation: 'Agriculture',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 20,
    description: 'Commercial',
    abbreviation: 'Commercial',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 20,
    description: 'Small Business',
    abbreviation: 'SmallBusiness',
    systemValue: '',
    sequence: 4,
    isDefault: false,
  },
];
export const getSourceTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 21,
    description: 'Stand Alone',
    abbreviation: 'Nova',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  { id: 2, systemEnumId: 21, description: 'LOS', abbreviation: 'LOS', systemValue: '', sequence: 2, isDefault: false },
];
export const getUserRoleList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 22,
    description: 'Administrator',
    abbreviation: 'Administrator',
    systemValue: '1',
    sequence: 1,
    isDefault: false,
  },
  {
    id: 2,
    systemEnumId: 22,
    description: 'Manager',
    abbreviation: 'Manager',
    systemValue: '0',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 22,
    description: 'User',
    abbreviation: 'User',
    systemValue: '0',
    sequence: 3,
    isDefault: true,
  },
];
export const getConsentTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 23,
    description: 'Application Terms',
    abbreviation: 'ApplicationTerms',
    systemValue: '',
    sequence: 1,
    isDefault: false,
  },
  {
    id: 2,
    systemEnumId: 23,
    description: 'Marketing Terms',
    abbreviation: 'MarketingTerms',
    systemValue: '',
    sequence: 2,
    isDefault: true,
  },
];
export const getCarrierRequestTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 24,
    description: 'Application Upload',
    abbreviation: 'ApplicationUpload',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 24,
    description: 'Submit Claim',
    abbreviation: 'SubmitClaim',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 24,
    description: 'Cancel Coverage',
    abbreviation: 'CancelCoverage',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 24,
    description: 'Update Info',
    abbreviation: 'UpdateInfo',
    systemValue: '',
    sequence: 4,
    isDefault: false,
  },
];
export const getCarrierRequestStatusList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 25,
    description: 'Submitted',
    abbreviation: 'Submitted',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 25,
    description: 'Complete',
    abbreviation: 'Complete',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 25,
    description: 'Pending',
    abbreviation: 'Pending',
    systemValue: '',
    sequence: 3,
    isDefault: true,
  },
  {
    id: 4,
    systemEnumId: 25,
    description: 'Approved',
    abbreviation: 'Approved',
    systemValue: '',
    sequence: 4,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 25,
    description: 'Declined',
    abbreviation: 'Declined',
    systemValue: '',
    sequence: 5,
    isDefault: false,
  },
  {
    id: 6,
    systemEnumId: 25,
    description: 'Expired',
    abbreviation: 'Expired',
    systemValue: '',
    sequence: 6,
    isDefault: false,
  },
  {
    id: 7,
    systemEnumId: 25,
    description: 'Terminated',
    abbreviation: 'Terminated',
    systemValue: '',
    sequence: 7,
    isDefault: false,
  },
  {
    id: 8,
    systemEnumId: 25,
    description: 'Cancelled',
    abbreviation: 'Cancelled',
    systemValue: '',
    sequence: 8,
    isDefault: false,
  },
  {
    id: 9,
    systemEnumId: 25,
    description: 'Paid',
    abbreviation: 'Paid',
    systemValue: '',
    sequence: 9,
    isDefault: false,
  },
  {
    id: 10,
    systemEnumId: 25,
    description: 'Updated',
    abbreviation: 'Updated',
    systemValue: '',
    sequence: 10,
    isDefault: false,
  },
  {
    id: 11,
    systemEnumId: 25,
    description: 'Failed',
    abbreviation: 'Failed',
    systemValue: '',
    sequence: 11,
    isDefault: false,
  },
];
export const getCancellationReasonList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 26,
    description: 'Closed Account',
    abbreviation: 'ClosedAccount',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 26,
    description: 'Early Payout',
    abbreviation: 'EarlyPayout',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 26,
    description: 'Have Other Insurance',
    abbreviation: 'HaveOtherInsurance',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 26,
    description: 'Maximum Age',
    abbreviation: 'MaximumAge',
    systemValue: '',
    sequence: 4,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 26,
    description: 'Misunderstood',
    abbreviation: 'Misunderstood',
    systemValue: '',
    sequence: 5,
    isDefault: false,
  },
  {
    id: 6,
    systemEnumId: 26,
    description: 'Too Expensive/Cost',
    abbreviation: 'TooExpensive/Cost',
    systemValue: '',
    sequence: 6,
    isDefault: false,
  },
  {
    id: 7,
    systemEnumId: 26,
    description: 'Loan in Arrears',
    abbreviation: 'LoaninArrears',
    systemValue: '',
    sequence: 7,
    isDefault: false,
  },
  {
    id: 8,
    systemEnumId: 26,
    description: 'Other',
    abbreviation: 'Other',
    systemValue: '',
    sequence: 8,
    isDefault: false,
  },
];
export const getReinstatementReasonList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 27,
    description: 'Cancelled in Error',
    abbreviation: 'CancelledinError',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 27,
    description: 'Cancelled Due to Payment in Arrears',
    abbreviation: 'CancelledDuetoPaymentinArrears',
    systemValue: '',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 27,
    description: 'Other',
    abbreviation: 'Other',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
];
export const getCoverageTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 28,
    description: 'Life',
    abbreviation: 'LIFE',
    systemValue: '100',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 28,
    description: 'Disability',
    abbreviation: 'DIS',
    systemValue: '200',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 28,
    description: 'Accidental Death',
    abbreviation: 'ADB',
    systemValue: '300',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 28,
    description: 'Critical Illness',
    abbreviation: 'CI',
    systemValue: '400',
    sequence: 4,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 28,
    description: 'Involuntary Unemployment',
    abbreviation: 'IUI',
    systemValue: '500',
    sequence: 5,
    isDefault: false,
  },
];
export const getPaymentTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 29,
    description: 'Blended',
    abbreviation: 'Blended',
    systemValue: '0',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 29,
    description: 'Interest Only',
    abbreviation: 'InterestOnly',
    systemValue: '1',
    sequence: 2,
    isDefault: false,
  },
  { id: 3, systemEnumId: 29, description: 'Fixed Principal Plus Accrued Interest', abbreviation: 'PnI', systemValue: '0', sequence: 3, isDefault: false },
  { id: 4, systemEnumId: 29, description: 'Balloon', abbreviation: 'Balloon', systemValue: '0', sequence: 4, isDefault: false },
  { id: 5, systemEnumId: 29, description: 'Lump Sum', abbreviation: 'LumpSum', systemValue: '1', sequence: 5, isDefault: false },
];
export const getPlaceOfBirthList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 30,
    description: 'Alberta',
    abbreviation: 'AB',
    systemValue: 'CA',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 30,
    description: 'British Columbia',
    abbreviation: 'BC',
    systemValue: 'CA',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 30,
    description: 'Manitoba',
    abbreviation: 'MB',
    systemValue: 'CA',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 30,
    description: 'New Brunswick',
    abbreviation: 'NB',
    systemValue: 'CA',
    sequence: 4,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 30,
    description: 'Newfoundland & Labrador',
    abbreviation: 'NL',
    systemValue: 'CA',
    sequence: 5,
    isDefault: false,
  },
  {
    id: 6,
    systemEnumId: 30,
    description: 'Northwest Territories',
    abbreviation: 'NT',
    systemValue: 'CA',
    sequence: 6,
    isDefault: false,
  },
  {
    id: 7,
    systemEnumId: 30,
    description: 'Nova Scotia',
    abbreviation: 'NS',
    systemValue: 'CA',
    sequence: 7,
    isDefault: false,
  },
  {
    id: 8,
    systemEnumId: 30,
    description: 'Nunavut',
    abbreviation: 'NU',
    systemValue: 'CA',
    sequence: 8,
    isDefault: false,
  },
  {
    id: 9,
    systemEnumId: 30,
    description: 'Ontario',
    abbreviation: 'ON',
    systemValue: 'CA',
    sequence: 9,
    isDefault: false,
  },
  {
    id: 10,
    systemEnumId: 30,
    description: 'Prince Edward Island',
    abbreviation: 'PE',
    systemValue: 'CA',
    sequence: 10,
    isDefault: false,
  },
  {
    id: 11,
    systemEnumId: 30,
    description: 'Quebec',
    abbreviation: 'QC',
    systemValue: 'CA',
    sequence: 11,
    isDefault: false,
  },
  {
    id: 12,
    systemEnumId: 30,
    description: 'Saskatchewan',
    abbreviation: 'SK',
    systemValue: 'CA',
    sequence: 12,
    isDefault: false,
  },
  {
    id: 13,
    systemEnumId: 30,
    description: 'Yukon',
    abbreviation: 'YT',
    systemValue: 'CA',
    sequence: 13,
    isDefault: false,
  },
  {
    id: 14,
    systemEnumId: 30,
    description: 'Alabama',
    abbreviation: 'AL',
    systemValue: 'USA',
    sequence: 14,
    isDefault: false,
  },
  {
    id: 15,
    systemEnumId: 30,
    description: 'Alaska',
    abbreviation: 'AK',
    systemValue: 'USA',
    sequence: 15,
    isDefault: false,
  },
  {
    id: 16,
    systemEnumId: 30,
    description: 'Arizona',
    abbreviation: 'AZ',
    systemValue: 'USA',
    sequence: 16,
    isDefault: false,
  },
  {
    id: 17,
    systemEnumId: 30,
    description: 'Arkansas',
    abbreviation: 'AR',
    systemValue: 'USA',
    sequence: 17,
    isDefault: false,
  },
  {
    id: 18,
    systemEnumId: 30,
    description: 'California',
    abbreviation: 'CA',
    systemValue: 'USA',
    sequence: 18,
    isDefault: false,
  },
  {
    id: 19,
    systemEnumId: 30,
    description: 'Colorado',
    abbreviation: 'CO',
    systemValue: 'USA',
    sequence: 19,
    isDefault: false,
  },
  {
    id: 20,
    systemEnumId: 30,
    description: 'Connecticut',
    abbreviation: 'CT',
    systemValue: 'USA',
    sequence: 20,
    isDefault: false,
  },
  {
    id: 21,
    systemEnumId: 30,
    description: 'Delaware',
    abbreviation: 'DE',
    systemValue: 'USA',
    sequence: 21,
    isDefault: false,
  },
  {
    id: 22,
    systemEnumId: 30,
    description: 'District of Columbia',
    abbreviation: 'DC',
    systemValue: 'USA',
    sequence: 22,
    isDefault: false,
  },
  {
    id: 23,
    systemEnumId: 30,
    description: 'Florida',
    abbreviation: 'FL',
    systemValue: 'USA',
    sequence: 23,
    isDefault: false,
  },
  {
    id: 24,
    systemEnumId: 30,
    description: 'Georgia',
    abbreviation: 'GA',
    systemValue: 'USA',
    sequence: 24,
    isDefault: false,
  },
  {
    id: 25,
    systemEnumId: 30,
    description: 'Hawaii',
    abbreviation: 'HI',
    systemValue: 'USA',
    sequence: 25,
    isDefault: false,
  },
  {
    id: 26,
    systemEnumId: 30,
    description: 'Idaho',
    abbreviation: 'ID',
    systemValue: 'USA',
    sequence: 26,
    isDefault: false,
  },
  {
    id: 27,
    systemEnumId: 30,
    description: 'Illinois',
    abbreviation: 'IL',
    systemValue: 'USA',
    sequence: 27,
    isDefault: false,
  },
  {
    id: 28,
    systemEnumId: 30,
    description: 'Indiana',
    abbreviation: 'IN',
    systemValue: 'USA',
    sequence: 28,
    isDefault: false,
  },
  {
    id: 29,
    systemEnumId: 30,
    description: 'Iowa',
    abbreviation: 'IA',
    systemValue: 'USA',
    sequence: 29,
    isDefault: false,
  },
  {
    id: 30,
    systemEnumId: 30,
    description: 'Kansas',
    abbreviation: 'KS',
    systemValue: 'USA',
    sequence: 30,
    isDefault: false,
  },
  {
    id: 31,
    systemEnumId: 30,
    description: 'Kentucky',
    abbreviation: 'KY',
    systemValue: 'USA',
    sequence: 31,
    isDefault: false,
  },
  {
    id: 32,
    systemEnumId: 30,
    description: 'Louisiana',
    abbreviation: 'LA',
    systemValue: 'USA',
    sequence: 32,
    isDefault: false,
  },
  {
    id: 33,
    systemEnumId: 30,
    description: 'Maine',
    abbreviation: 'ME',
    systemValue: 'USA',
    sequence: 33,
    isDefault: false,
  },
  {
    id: 34,
    systemEnumId: 30,
    description: 'Maryland',
    abbreviation: 'MD',
    systemValue: 'USA',
    sequence: 34,
    isDefault: false,
  },
  {
    id: 35,
    systemEnumId: 30,
    description: 'Massachusetts',
    abbreviation: 'MA',
    systemValue: 'USA',
    sequence: 35,
    isDefault: false,
  },
  {
    id: 36,
    systemEnumId: 30,
    description: 'Michigan',
    abbreviation: 'MI',
    systemValue: 'USA',
    sequence: 36,
    isDefault: false,
  },
  {
    id: 37,
    systemEnumId: 30,
    description: 'Minnesota',
    abbreviation: 'MN',
    systemValue: 'USA',
    sequence: 37,
    isDefault: false,
  },
  {
    id: 38,
    systemEnumId: 30,
    description: 'Mississippi',
    abbreviation: 'MS',
    systemValue: 'USA',
    sequence: 38,
    isDefault: false,
  },
  {
    id: 39,
    systemEnumId: 30,
    description: 'Missouri',
    abbreviation: 'MO',
    systemValue: 'USA',
    sequence: 39,
    isDefault: false,
  },
  {
    id: 40,
    systemEnumId: 30,
    description: 'Montana',
    abbreviation: 'MT',
    systemValue: 'USA',
    sequence: 40,
    isDefault: false,
  },
  {
    id: 41,
    systemEnumId: 30,
    description: 'Nebraska',
    abbreviation: 'NE',
    systemValue: 'USA',
    sequence: 41,
    isDefault: false,
  },
  {
    id: 42,
    systemEnumId: 30,
    description: 'Nevada',
    abbreviation: 'NV',
    systemValue: 'USA',
    sequence: 42,
    isDefault: false,
  },
  {
    id: 43,
    systemEnumId: 30,
    description: 'New Hampshire',
    abbreviation: 'NH',
    systemValue: 'USA',
    sequence: 43,
    isDefault: false,
  },
  {
    id: 44,
    systemEnumId: 30,
    description: 'New Jersey',
    abbreviation: 'NJ',
    systemValue: 'USA',
    sequence: 44,
    isDefault: false,
  },
  {
    id: 45,
    systemEnumId: 30,
    description: 'New Mexico',
    abbreviation: 'NM',
    systemValue: 'USA',
    sequence: 45,
    isDefault: false,
  },
  {
    id: 46,
    systemEnumId: 30,
    description: 'New York',
    abbreviation: 'NY',
    systemValue: 'USA',
    sequence: 46,
    isDefault: false,
  },
  {
    id: 47,
    systemEnumId: 30,
    description: 'North Carolina',
    abbreviation: 'NC',
    systemValue: 'USA',
    sequence: 47,
    isDefault: false,
  },
  {
    id: 48,
    systemEnumId: 30,
    description: 'North Dakota',
    abbreviation: 'ND',
    systemValue: 'USA',
    sequence: 48,
    isDefault: false,
  },
  {
    id: 49,
    systemEnumId: 30,
    description: 'Ohio',
    abbreviation: 'OH',
    systemValue: 'USA',
    sequence: 49,
    isDefault: false,
  },
  {
    id: 50,
    systemEnumId: 30,
    description: 'Oklahoma',
    abbreviation: 'OK',
    systemValue: 'USA',
    sequence: 50,
    isDefault: false,
  },
  {
    id: 51,
    systemEnumId: 30,
    description: 'Oregon',
    abbreviation: 'OR',
    systemValue: 'USA',
    sequence: 51,
    isDefault: false,
  },
  {
    id: 52,
    systemEnumId: 30,
    description: 'Pennsylvania',
    abbreviation: 'PA',
    systemValue: 'USA',
    sequence: 52,
    isDefault: false,
  },
  {
    id: 53,
    systemEnumId: 30,
    description: 'Rhode Island',
    abbreviation: 'RI',
    systemValue: 'USA',
    sequence: 53,
    isDefault: false,
  },
  {
    id: 54,
    systemEnumId: 30,
    description: 'South Carolina',
    abbreviation: 'SC',
    systemValue: 'USA',
    sequence: 54,
    isDefault: false,
  },
  {
    id: 55,
    systemEnumId: 30,
    description: 'South Dakota',
    abbreviation: 'SD',
    systemValue: 'USA',
    sequence: 55,
    isDefault: false,
  },
  {
    id: 56,
    systemEnumId: 30,
    description: 'Tennessee',
    abbreviation: 'TN',
    systemValue: 'USA',
    sequence: 56,
    isDefault: false,
  },
  {
    id: 57,
    systemEnumId: 30,
    description: 'Texas',
    abbreviation: 'TX',
    systemValue: 'USA',
    sequence: 57,
    isDefault: false,
  },
  {
    id: 58,
    systemEnumId: 30,
    description: 'Utah',
    abbreviation: 'UT',
    systemValue: 'USA',
    sequence: 58,
    isDefault: false,
  },
  {
    id: 59,
    systemEnumId: 30,
    description: 'Vermont',
    abbreviation: 'VT',
    systemValue: 'USA',
    sequence: 59,
    isDefault: false,
  },
  {
    id: 60,
    systemEnumId: 30,
    description: 'Virginia',
    abbreviation: 'VA',
    systemValue: 'USA',
    sequence: 60,
    isDefault: false,
  },
  {
    id: 61,
    systemEnumId: 30,
    description: 'Washington',
    abbreviation: 'WA',
    systemValue: 'USA',
    sequence: 61,
    isDefault: false,
  },
  {
    id: 62,
    systemEnumId: 30,
    description: 'West Virginia',
    abbreviation: 'WV',
    systemValue: 'USA',
    sequence: 62,
    isDefault: false,
  },
  {
    id: 63,
    systemEnumId: 30,
    description: 'Wisconsin',
    abbreviation: 'WI',
    systemValue: 'USA',
    sequence: 63,
    isDefault: false,
  },
  {
    id: 64,
    systemEnumId: 30,
    description: 'Wyoming',
    abbreviation: 'WY',
    systemValue: 'USA',
    sequence: 64,
    isDefault: false,
  },
  {
    id: 65,
    systemEnumId: 30,
    description: 'Other',
    abbreviation: 'OTHER',
    systemValue: 'OTHER',
    sequence: 65,
    isDefault: false,
  },
];
export const getErrorCodeList = (): EnumValue[] => [
  {
    id: 3,
    systemEnumId: 31,
    description: 'CU Config File is missing.',
    abbreviation: '3',
    systemValue: '',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 10,
    systemEnumId: 31,
    description: 'Invalid payment frequency.',
    abbreviation: '10',
    systemValue: '',
    sequence: 10,
    isDefault: false,
  },
  {
    id: 11,
    systemEnumId: 31,
    description: 'Invalid funding date.',
    abbreviation: '11',
    systemValue: '',
    sequence: 11,
    isDefault: false,
  },
  {
    id: 12,
    systemEnumId: 31,
    description: 'Invalid funding date.',
    abbreviation: '12',
    systemValue: '',
    sequence: 12,
    isDefault: false,
  },
  {
    id: 13,
    systemEnumId: 31,
    description: 'Invalid first payment date.',
    abbreviation: '13',
    systemValue: '',
    sequence: 13,
    isDefault: false,
  },
  {
    id: 20,
    systemEnumId: 31,
    description: 'Missing interest rate.',
    abbreviation: '20',
    systemValue: '',
    sequence: 20,
    isDefault: false,
  },
  {
    id: 23,
    systemEnumId: 31,
    description: 'Your requested first interval (Funding Date to First Payment) is too long.',
    abbreviation: '23',
    systemValue: '',
    sequence: 23,
    isDefault: false,
  },
  {
    id: 24,
    systemEnumId: 31,
    description: 'Credit insurance may not be available for your requested type.',
    abbreviation: '24',
    systemValue: '',
    sequence: 24,
    isDefault: false,
  },
  {
    id: 34,
    systemEnumId: 31,
    description: 'Coverage is not available. The requested coverage is outside the allowable limits.',
    abbreviation: '34',
    systemValue: '',
    sequence: 34,
    isDefault: false,
  },
  {
    id: 35,
    systemEnumId: 31,
    description: 'Coverage is not available. The requested coverage is outside the allowable limits.',
    abbreviation: '35',
    systemValue: '',
    sequence: 35,
    isDefault: false,
  },
  {
    id: 37,
    systemEnumId: 31,
    description: 'Coverage is not available. The requested coverage is outside the allowable limits.',
    abbreviation: '37',
    systemValue: '',
    sequence: 37,
    isDefault: false,
  },
  {
    id: 39,
    systemEnumId: 31,
    description: 'Coverage is not available. The requested coverage is outside the allowable limits.',
    abbreviation: '39',
    systemValue: '',
    sequence: 39,
    isDefault: false,
  },
  {
    id: 41,
    systemEnumId: 31,
    description:
      'The current maximum number of payments has been exceeded. Please reduce the number of payments and recalculate.',
    abbreviation: '41',
    systemValue: '',
    sequence: 41,
    isDefault: false,
  },
  {
    id: 49,
    systemEnumId: 31,
    description: 'Coverage is not available. The requested coverage is outside the allowable limits.',
    abbreviation: '49',
    systemValue: '',
    sequence: 49,
    isDefault: false,
  },
  {
    id: 50,
    systemEnumId: 31,
    description:
      'The payment amount does not cover the amount of interest due in the first period causing a possible negative amortization.',
    abbreviation: '50',
    systemValue: '',
    sequence: 50,
    isDefault: false,
  },
  {
    id: 92,
    systemEnumId: 31,
    description: 'Term of loan exceeded maximum loan term allowed.',
    abbreviation: '92',
    systemValue: '',
    sequence: 92,
    isDefault: false,
  },
  {
    id: 98,
    systemEnumId: 31,
    description:
      'The current maximum number of payments has been exceeded. Please reduce the number of payments and recalculate.',
    abbreviation: '98',
    systemValue: '',
    sequence: 98,
    isDefault: false,
  },
  {
    id: 113,
    systemEnumId: 31,
    description: 'Term of Disability coverage exceeded maximum coverage term allowed.',
    abbreviation: '113',
    systemValue: '',
    sequence: 113,
    isDefault: false,
  },
  {
    id: 114,
    systemEnumId: 31,
    description: 'Term of Life coverage exceeded maximum coverage term allowed.',
    abbreviation: '114',
    systemValue: '',
    sequence: 114,
    isDefault: false,
  },
  {
    id: 115,
    systemEnumId: 31,
    description: 'Term of IUI coverage exceeded maximum coverage term allowed.',
    abbreviation: '115',
    systemValue: '',
    sequence: 115,
    isDefault: false,
  },
  {
    id: 117,
    systemEnumId: 31,
    description: 'Term of ADB coverage exceeded maximum coverage term allowed.',
    abbreviation: '117',
    systemValue: '',
    sequence: 117,
    isDefault: false,
  },
  {
    id: 122,
    systemEnumId: 31,
    description: 'Term of CI coverage exceeded maximum coverage term allowed.',
    abbreviation: '122',
    systemValue: '',
    sequence: 122,
    isDefault: false,
  },
  {
    id: 130,
    systemEnumId: 31,
    description: 'Insurance percent override not allowed.',
    abbreviation: '130',
    systemValue: '',
    sequence: 130,
    isDefault: false,
  },
];
export const getReturnCodeList = (): EnumValue[] => [
  {
    id: 30,
    systemEnumId: 32,
    description: 'Applicant Ineligible for Life Insurance',
    abbreviation: '30',
    systemValue: '',
    sequence: 30,
    isDefault: false,
  },
  {
    id: 31,
    systemEnumId: 32,
    description: 'Applicant Ineligible for DIS',
    abbreviation: '31',
    systemValue: '',
    sequence: 31,
    isDefault: false,
  },
  {
    id: 32,
    systemEnumId: 32,
    description: 'Applicant Ineligible for IUI',
    abbreviation: '32',
    systemValue: '',
    sequence: 32,
    isDefault: false,
  },
  {
    id: 33,
    systemEnumId: 32,
    description: 'Co-Applicant Ineligible for Life Insurance',
    abbreviation: '33',
    systemValue: '',
    sequence: 33,
    isDefault: false,
  },
  {
    id: 34,
    systemEnumId: 32,
    description: 'Co-Applicant Ineligible for DIS',
    abbreviation: '34',
    systemValue: '',
    sequence: 34,
    isDefault: false,
  },
  {
    id: 35,
    systemEnumId: 32,
    description: 'Co-Applicant Ineligible for IUI',
    abbreviation: '35',
    systemValue: '',
    sequence: 35,
    isDefault: false,
  },
  {
    id: 36,
    systemEnumId: 32,
    description: 'Applicant Ineligible for CI',
    abbreviation: '36',
    systemValue: '',
    sequence: 36,
    isDefault: false,
  },
  {
    id: 37,
    systemEnumId: 32,
    description: 'Co-Applicant Ineligible for CI',
    abbreviation: '37',
    systemValue: '',
    sequence: 37,
    isDefault: false,
  },
  {
    id: 38,
    systemEnumId: 32,
    description: 'Applicant Ineligible for Debt Protection',
    abbreviation: '38',
    systemValue: '',
    sequence: 38,
    isDefault: false,
  },
  {
    id: 39,
    systemEnumId: 32,
    description: 'Co-Applicant Ineligible for Debt Protection',
    abbreviation: '39',
    systemValue: '',
    sequence: 39,
    isDefault: false,
  },
  {
    id: 40,
    systemEnumId: 32,
    description: 'Co-Applicant Age Used',
    abbreviation: '40',
    systemValue: '',
    sequence: 40,
    isDefault: false,
  },
  {
    id: 41,
    systemEnumId: 32,
    description: 'Applicant Ineligible for Life Insurance',
    abbreviation: '41',
    systemValue: '',
    sequence: 41,
    isDefault: false,
  },
  {
    id: 42,
    systemEnumId: 32,
    description: 'Applicant Ineligible for DIS',
    abbreviation: '42',
    systemValue: '',
    sequence: 42,
    isDefault: false,
  },
  {
    id: 43,
    systemEnumId: 32,
    description: 'Applicant Ineligible for IUI',
    abbreviation: '43',
    systemValue: '',
    sequence: 43,
    isDefault: false,
  },
  {
    id: 44,
    systemEnumId: 32,
    description: 'Co-Applicant Ineligible for Life Insurance',
    abbreviation: '44',
    systemValue: '',
    sequence: 44,
    isDefault: false,
  },
  {
    id: 45,
    systemEnumId: 32,
    description: 'Co-Applicant Ineligible for DIS',
    abbreviation: '45',
    systemValue: '',
    sequence: 45,
    isDefault: false,
  },
  {
    id: 46,
    systemEnumId: 32,
    description: 'Co-Applicant Ineligible for IUI',
    abbreviation: '46',
    systemValue: '',
    sequence: 46,
    isDefault: false,
  },
  {
    id: 47,
    systemEnumId: 32,
    description: 'Applicant Ineligible for CI',
    abbreviation: '47',
    systemValue: '',
    sequence: 47,
    isDefault: false,
  },
  {
    id: 48,
    systemEnumId: 32,
    description: 'Applicant Ineligible for CI',
    abbreviation: '48',
    systemValue: '',
    sequence: 48,
    isDefault: false,
  },
  {
    id: 49,
    systemEnumId: 32,
    description: 'Applicant Ineligible for Debt Protection',
    abbreviation: '49',
    systemValue: '',
    sequence: 49,
    isDefault: false,
  },
  {
    id: 50,
    systemEnumId: 32,
    description: 'Co-Applicant Ineligible for Debt Protection',
    abbreviation: '50',
    systemValue: '',
    sequence: 50,
    isDefault: false,
  },
  {
    id: 51,
    systemEnumId: 32,
    description: 'Coverage will terminate due to age before the end of the loan.',
    abbreviation: '51',
    systemValue: '',
    sequence: 51,
    isDefault: false,
  },
  {
    id: 52,
    systemEnumId: 32,
    description: 'Coverage has exceeded product limits. Review coverage amount and coverage duration.',
    abbreviation: '52',
    systemValue: '',
    sequence: 52,
    isDefault: false,
  },
  {
    id: 53,
    systemEnumId: 32,
    description: 'Coverage has exceeded product limits. Review coverage amount and coverage duration.',
    abbreviation: '53',
    systemValue: '',
    sequence: 53,
    isDefault: false,
  },
  {
    id: 54,
    systemEnumId: 32,
    description: 'Coverage will terminate due to age before the end of the loan.',
    abbreviation: '54',
    systemValue: '',
    sequence: 54,
    isDefault: false,
  },
  {
    id: 55,
    systemEnumId: 32,
    description: 'Coverage has exceeded product limits. Review coverage amount and duration.',
    abbreviation: '55',
    systemValue: '',
    sequence: 55,
    isDefault: false,
  },
  {
    id: 56,
    systemEnumId: 32,
    description: 'Coverage has exceeded product limits. Review coverage amount and duration.',
    abbreviation: '56',
    systemValue: '',
    sequence: 56,
    isDefault: false,
  },
  {
    id: 57,
    systemEnumId: 32,
    description: 'Coverage will terminate due to age before the end of the loan.',
    abbreviation: '57',
    systemValue: '',
    sequence: 57,
    isDefault: false,
  },
  {
    id: 58,
    systemEnumId: 32,
    description: 'Coverage will terminate due to age before the end of the loan.',
    abbreviation: '58',
    systemValue: '',
    sequence: 58,
    isDefault: false,
  },
  {
    id: 67,
    systemEnumId: 32,
    description: 'Loan exceeds maximum coverage. Coverage has been reduced.',
    abbreviation: '67',
    systemValue: '',
    sequence: 67,
    isDefault: false,
  },
  {
    id: 68,
    systemEnumId: 32,
    description: 'Loan exceeds maximum coverage. Coverage has been reduced.',
    abbreviation: '68',
    systemValue: '',
    sequence: 68,
    isDefault: false,
  },
  {
    id: 69,
    systemEnumId: 32,
    description: 'Insurance Truncated',
    abbreviation: '69',
    systemValue: '',
    sequence: 69,
    isDefault: false,
  },
];
export const getBranchAddressTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 33,
    description: 'Branch',
    abbreviation: 'Branch',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
];
export const getBranchPhoneTypeList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 34,
    description: 'Branch',
    abbreviation: 'Branch',
    systemValue: '',
    sequence: 1,
    isDefault: true,
  },
];


export const getChannelTypeNewList = (): EnumValue[] => [
  {
    id: 1,
    systemEnumId: 29,
    description: 'In-Branch',
    abbreviation: 'In-Branch',
    systemValue: '1',
    sequence: 1,
    isDefault: true,
  },
  {
    id: 2,
    systemEnumId: 29,
    description: 'Mortgage Specialist',
    abbreviation: 'Mortgage Specialist',
    systemValue: '2',
    sequence: 2,
    isDefault: false,
  },
  {
    id: 3,
    systemEnumId: 29,
    description: 'Walk-In',
    abbreviation: 'Walk-In',
    systemValue: '3',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 4,
    systemEnumId: 29,
    description: 'Dealer',
    abbreviation: 'Dealer',
    systemValue: '4',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 5,
    systemEnumId: 29,
    description: 'Mortgage Broker',
    abbreviation: 'Mortgage Broker',
    systemValue: '5',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 6,
    systemEnumId: 29,
    description: 'Broker Center',
    abbreviation: 'Broker Center',
    systemValue: '6',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 7,
    systemEnumId: 29,
    description: 'Referred to FP',
    abbreviation: 'Referred to FP',
    systemValue: '7',
    sequence: 3,
    isDefault: false,
  },
  {
    id: 8,
    systemEnumId: 29,
    description: 'Digital Lending',
    abbreviation: 'Digital Lending',
    systemValue: '8',
    sequence: 3,
    isDefault: false,
  }
];