export interface QuickQuoteMPDto {
  LendingOfficer?: string;
  LendingOfficerEmail?: string;
  LendingOfficerPhone?: string;
  LenderBranch?: string;
  FormDate?: string;
  LoanType?: string;
  InsuranceType?: string;
  LoanAmount?: string;
  PaymentAmount?: string;
  PaymentFrequency?: string;
  PaymentType?: string;
  FundingDate?: string;
  FirstPaymentDate?: string;
  InterestRate?: string;
  LoanTerm?: string;
  Amortization?: string;
  LoanAmountCovered?: string;
  LoanPaymentAmountCovered?: string;
  PremiumPaymentAmount?: string;
  InsuredLoan?: string;
  InsuredLoanPercentAmount?: string;
  InsuredPaymentPercentAmount?: string;
  ADBCoveragePercent?: string;
  CICoveragePercent?: string;
  IUICoveragePercent?: string;
  InsuranceAmortization?: string;
  FirstApplicationNames?: string;
  SecondApplicationNames?: string;
  FirstApplicationLIFEPremiumAmount?: string;
  FirstApplicationDISPremiumAmount?: string;
  FirstApplicationCIPremiumAmount?: string;
  FirstApplicationIUIPremiumAmount?: string;
  FirstApplicationADBPremiumAmount?: string;
  FirstApplicationPremiumPaymentAmount?: string;
  FirstApplicationLIFEInsuredAmount?: string;
  FirstApplicationDISInsuredAmount?: string;
  FirstApplicationCIInsuredAmount?: string;
  FirstApplicationIUIInsuredAmount?: string;
  FirstApplicationADBInsuredAmount?: string;
  SecondApplicationLIFEPremiumAmount?: string;
  SecondApplicationDISPremiumAmount?: string;
  SecondApplicationCIPremiumAmount?: string;
  SecondApplicationIUIPremiumAmount?: string;
  SecondApplicationADBPremiumAmount?: string;
  SecondApplicationPremiumPaymentAmount?: string;
  SecondApplicationLIFEInsuredAmount?: string;
  SecondApplicationDISInsuredAmount?: string;
  SecondApplicationCIInsuredAmount?: string;
  SecondApplicationIUIInsuredAmount?: string;
  SecondApplicationADBInsuredAmount?: string;
  PrimaryApplicantName?: string;
  PrimaryBirthDate?: string;
  PrimaryIsSmoker?: string;
  PrimarySelfEmployed?: string;
  PrimaryWorkHours?: string;
  PrimaryProvince?: string;
  PrimaryLIFECoverageCode?: string;
  PrimaryDISCoverageCode?: string;
  PrimaryADBCoverageCode?: string;
  PrimaryCICoverageCode?: string;
  PrimaryIUICoverageCode?: string;
  PrimaryLIFEPremiumAmount?: string;
  PrimaryLIFEInsuredAmount?: string;
  PrimaryDISPremiumAmount?: string;
  PrimaryDISInsuredAmount?: string;
  PrimaryADBPremiumAmount?: string;
  PrimaryADBInsuredAmount?: string;
  PrimaryCIPremiumAmount?: string;
  PrimaryCIInsuredAmount?: string;
  PrimaryIUIPremiumAmount?: string;
  PrimaryIUIInsuredAmount?: string;
  SecondaryApplicantName?: string;
  SecondaryBirthDate?: string;
  SecondaryIsSmoker?: string;
  SecondarySelfEmployed?: string;
  SecondaryWorkHours?: string;
  SecondaryProvince?: string;
  SecondaryLIFECoverageCode?: string;
  SecondaryDISCoverageCode?: string;
  SecondaryADBCoverageCode?: string;
  SecondaryCICoverageCode?: string;
  SecondaryIUICoverageCode?: string;
  SecondaryLIFEPremiumAmount?: string;
  SecondaryLIFEInsuredAmount?: string;
  SecondaryDISPremiumAmount?: string;
  SecondaryDISInsuredAmount?: string;
  SecondaryADBPremiumAmount?: string;
  SecondaryADBInsuredAmount?: string;
  SecondaryCIPremiumAmount?: string;
  SecondaryCIInsuredAmount?: string;
  SecondaryIUIPremiumAmount?: string;
  SecondaryIUIInsuredAmount?: string;
  TertiaryApplicantName?: string;
  TertiaryBirthDate?: string;
  TertiaryIsSmoker?: string;
  TertiarySelfEmployed?: string;
  TertiaryWorkHours?: string;
  TertiaryProvince?: string;
  TertiaryLIFECoverageCode?: string;
  TertiaryDISCoverageCode?: string;
  TertiaryADBCoverageCode?: string;
  TertiaryCICoverageCode?: string;
  TertiaryIUICoverageCode?: string;
  TertiaryLIFEPremiumAmount?: string;
  TertiaryLIFEInsuredAmount?: string;
  TertiaryDISPremiumAmount?: string;
  TertiaryDISInsuredAmount?: string;
  TertiaryADBPremiumAmount?: string;
  TertiaryADBInsuredAmount?: string;
  TertiaryCIPremiumAmount?: string;
  TertiaryCIInsuredAmount?: string;
  TertiaryIUIPremiumAmount?: string;
  TertiaryIUIInsuredAmount?: string;
  QuaternaryApplicantName?: string;
  QuaternaryBirthDate?: string;
  QuaternaryIsSmoker?: string;
  QuaternarySelfEmployed?: string;
  QuaternaryWorkHours?: string;
  QuaternaryProvince?: string;
  QuaternaryLIFECoverageCode?: string;
  QuaternaryDISCoverageCode?: string;
  QuaternaryADBCoverageCode?: string;
  QuaternaryCICoverageCode?: string;
  QuaternaryIUICoverageCode?: string;
  QuaternaryLIFEPremiumAmount?: string;
  QuaternaryLIFEInsuredAmount?: string;
  QuaternaryDISPremiumAmount?: string;
  QuaternaryDISInsuredAmount?: string;
  QuaternaryADBPremiumAmount?: string;
  QuaternaryADBInsuredAmount?: string;
  QuaternaryCIPremiumAmount?: string;
  QuaternaryCIInsuredAmount?: string;
  QuaternaryIUIPremiumAmount?: string;
  QuaternaryIUIInsuredAmount?: string;
}

export const getStringifyQuickQuote = () => {
  const valueDto: QuickQuoteMPDto = {
    LendingOfficer: 'Test Admin',
    LendingOfficerEmail: 'testadmin@coastcapitalsavings.com',
    LendingOfficerPhone: '6474102833',
    LenderBranch: 'Kelowna',
    FormDate: '2024-06-06T00:00:00',
    LoanType: 'Mortgage',
    InsuranceType: 'MO',
    LoanAmount: '350.000',
    PaymentAmount: '10000',
    PaymentFrequency: 'Monthly',
    PaymentType: 'Blended',
    FundingDate: '2024-06-06',
    FirstPaymentDate: '2024-07-06',
    InterestRate: '4.5',
    LoanTerm: '0',
    Amortization: '0',
    LoanAmountCovered: '4000',
    LoanPaymentAmountCovered: '4000',
    PremiumPaymentAmount: '4000',
    ADBCoveragePercent: '100',
    CICoveragePercent: '100',
    IUICoveragePercent: '100',
    InsuranceAmortization: '0',
    FirstApplicationNames: 'First Applicant, Third Applicant',
    SecondApplicationNames: 'Second Applicant, Quaternary Applicant',
    PrimaryApplicantName: 'First Applicant',
    PrimaryBirthDate: '1987-01-01T00:00:00',
    PrimaryIsSmoker: 'No',
    PrimarySelfEmployed: 'No',
    PrimaryWorkHours: '20',
    PrimaryProvince: 'ON',
    PrimaryLIFECoverageCode: '100',
    PrimaryDISCoverageCode: '200',
    PrimaryADBCoverageCode: '300',
    PrimaryCICoverageCode: '400',
    PrimaryIUICoverageCode: '500',
    PrimaryLIFEPremiumAmount: '6000',
    PrimaryLIFEInsuredAmount: '2000',
    PrimaryDISPremiumAmount: '7000',
    PrimaryDISInsuredAmount: '2000',
    PrimaryADBPremiumAmount: '3000',
    PrimaryADBInsuredAmount: '2000',
    PrimaryCIPremiumAmount: '3000',
    PrimaryCIInsuredAmount: '2000',
    PrimaryIUIPremiumAmount: '4000',
    PrimaryIUIInsuredAmount: '2000',
    SecondaryApplicantName: 'Second Applicant',
    SecondaryBirthDate: '1987-01-01T00:00:00',
    SecondaryIsSmoker: 'No',
    SecondarySelfEmployed: 'No',
    SecondaryWorkHours: '20',
    SecondaryProvince: 'ON',
    SecondaryLIFECoverageCode: '100',
    SecondaryDISCoverageCode: '200',
    SecondaryADBCoverageCode: '300',
    SecondaryCICoverageCode: '400',
    SecondaryIUICoverageCode: '500',
    SecondaryLIFEPremiumAmount: '6000',
    SecondaryLIFEInsuredAmount: '2000',
    SecondaryDISPremiumAmount: '7000',
    SecondaryDISInsuredAmount: '2000',
    SecondaryADBPremiumAmount: '3000',
    SecondaryADBInsuredAmount: '2000',
    SecondaryCIPremiumAmount: '3000',
    SecondaryCIInsuredAmount: '2000',
    SecondaryIUIPremiumAmount: '4000',
    SecondaryIUIInsuredAmount: '2000',
    TertiaryApplicantName: 'Third Applicant',
    TertiaryBirthDate: '1987-01-01T00:00:00',
    TertiaryIsSmoker: 'No',
    TertiarySelfEmployed: 'No',
    TertiaryWorkHours: '20',
    TertiaryProvince: 'ON',
    TertiaryLIFECoverageCode: '100',
    TertiaryDISCoverageCode: '200',
    TertiaryADBCoverageCode: '300',
    TertiaryCICoverageCode: '400',
    TertiaryIUICoverageCode: '500',
    TertiaryLIFEPremiumAmount: '6000',
    TertiaryLIFEInsuredAmount: '2000',
    TertiaryDISPremiumAmount: '7000',
    TertiaryDISInsuredAmount: '2000',
    TertiaryADBPremiumAmount: '3000',
    TertiaryADBInsuredAmount: '2000',
    TertiaryCIPremiumAmount: '3000',
    TertiaryCIInsuredAmount: '2000',
    TertiaryIUIPremiumAmount: '4000',
    TertiaryIUIInsuredAmount: '2000',
    QuaternaryApplicantName: 'Fourth Applicant',
    QuaternaryBirthDate: '1987-01-01T00:00:00',
    QuaternaryIsSmoker: 'No',
    QuaternarySelfEmployed: 'No',
    QuaternaryWorkHours: '20',
    QuaternaryProvince: 'ON',
    QuaternaryLIFECoverageCode: '100',
    QuaternaryDISCoverageCode: '200',
    QuaternaryADBCoverageCode: '300',
    QuaternaryCICoverageCode: '400',
    QuaternaryIUICoverageCode: '500',
    QuaternaryLIFEPremiumAmount: '6000',
    QuaternaryLIFEInsuredAmount: '2000',
    QuaternaryDISPremiumAmount: '7000',
    QuaternaryDISInsuredAmount: '2000',
    QuaternaryADBPremiumAmount: '3000',
    QuaternaryADBInsuredAmount: '2000',
    QuaternaryCIPremiumAmount: '3000',
    QuaternaryCIInsuredAmount: '2000',
    QuaternaryIUIPremiumAmount: '4000.00',
    QuaternaryIUIInsuredAmount: '2000.00',
  };

  return JSON.stringify(valueDto);
};

export interface FormMetadataDto {
  formType: string;
  formIdentifier: string;
  templateName: string;
  formData: string;
}
